spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/payment
    username: root
    password: 1234

  datasource:
    driver-class-name: com.mysql.jdbc.Driver

  thymeleaf:
    cache: false

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          configuration:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
            value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
        bindings:
          send-out-0:
            producer:
              record-metadata-channel: payment-result
      bindings:
        send-out-0:
          destination: payment
          group: payment-service




PSP:
  toss:
    secretKey: "test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6"
    url: https://api.tosspayments.com